### ISSUE TITLE
Ability to edit an expense

### ISSUE THREAD

**Issue by vishwa5854** [oss-apps/split-pro#59] opened 2024-05-15 14:46 UTC
I think it would be really great if we can edit the expense after we add it, edits can include adding and removing people, changing the title, changing the total expense etc.

All of these features are available on splitwise and I kind of miss them.

**Comment by jambt** [comment] 2024-06-10 19:41
Changing date and category is also very often used in my usecase (which is: inputting it wrong in the first place).

**Comment by KMKoushik** [comment] 2024-06-11 03:42
@jambt Agree, I'm getting lot's of requests for edit feature. Will work on it

**Comment by KMKoushik** [comment] 2024-10-01 21:07
Duplicate of #115

**Closed by KMKoushik** 2024-10-01 21:07 UTC
Labels: enhancement
