### ISSUE TITLE
Allow to edit an expense

### ISSUE THREAD

**Issue by lucasmarinb** [oss-apps/split-pro#74] opened 2024-08-05 02:37 UTC
It would be nice to be able to edit an expense, since right now it's only possible to delete the expense and create a new one.

**Comment by ShrihariMohan** [comment] 2024-08-26 13:45
Duplicate of https://github.com/oss-apps/split-pro/issues/59

**Comment by ShrihariMohan** [comment] 2024-08-31 12:12
I am working on it

**Comment by KMKoushik** [comment] 2024-10-01 21:07
Duplicate of #115

**Closed by KMKoushik** 2024-10-01 21:07 UTC
Labels: enhancement
